export const CityOptions = [
    { value: 0, label: 'Виберіть місто' },
    { value: 1, label: 'Київ' },
    { value: 2, label: 'Львів' },
    { value: 3, label: 'Харків' },
    { value: 4, label: 'Одеса' },
    { value: 5, label: 'Дніпро' },
    { value: 6, label: 'Запоріжжя' },
    { value: 7, label: 'Вінниця' },
    { value: 8, label: 'Черкаси' },
    { value: 9, label: 'Івано-Франківськ' },
    { value: 10, label: 'Тернопіль' },
    { value: 11, label: 'Рівне' },
    { value: 12, label: 'Житомир' },
    { value: 13, label: 'Суми' },
    { value: 14, label: 'Полтава' },
    { value: 15, label: 'Чернігів' },
    { value: 16, label: 'Кропивницький' },
    { value: 17, label: 'Луцьк' },
    { value: 18, label: 'Хмельницький' },
    { value: 19, label: 'Миколаїв' },
    { value: 20, label: 'Чернівці' },
    { value: 21, label: 'Ужгород' },
    { value: 22, label: 'Берегове' },
    { value: 23, label: 'Кам\'янець-Подільський' },
    { value: 24, label: 'Кам\'янське' },
    { value: 25, label: 'Біла Церква' },
    { value: 26, label: 'Бровари' },
    { value: 27, label: 'Херсон' },
    { value: 28, label: 'Мукачево' },
    { value: 29, label: 'Кременчук' },
    { value: 30, label: 'Конотоп' },
    { value: 31, label: 'Умань' },
    { value: 32, label: 'Кривий Ріг' }
];