export const CityOptions = [
    { value: 'kyiv', label: 'Київ' },
    { value: 'lviv', label: 'Львів' },
    { value: 'odessa', label: 'Одеса' },
    { value: 'kharkiv', label: 'Харків' },
    { value: 'dnipro', label: 'Дніпро' },
    { value: 'zaporizhzhia', label: 'Запоріжжя' },
    { value: 'vinnytsia', label: 'Вінниця' },
    { value: 'cherkasy', label: 'Черкаси' },
    { value: 'ivano-frankivsk', label: 'Івано-Франківськ' },
    { value: 'ternopil', label: 'Тернопіль' },
    { value: 'rivne', label: 'Рівне' },
    { value: 'zhytomyr', label: 'Житомир' },
    { value: 'sumy', label: 'Суми' },
    { value: 'poltava', label: 'Полтава' },
    { value: 'chernihiv', label: 'Чернігів' },
    { value: 'kropyvnytskyi', label: 'Кропивницький' },
    { value: 'lutsk', label: 'Луцьк' },
    { value: 'khmelnytskyi', label: 'Хмельницький' },
    { value: 'mykolaiv', label: 'Миколаїв' },
    { value: 'chernivtsi', label: 'Чернівці' },
    { value: 'uzhhorod', label: 'Ужгород' },
    { value: 'berehove', label: 'Берегове' },
    { value: 'kamianets-podilskyi', label: 'Кам\'янець-Подільський' },
    { value: 'kamianske', label: 'Кам\'янське' },
    { value: 'bila-tserkva', label: 'Біла Церква' },
    { value: 'brovary', label: 'Бровари' },
    { value: 'kherson', label: 'Херсон' },
    { value: 'mukachevo', label: 'Мукачево' },
    { value: 'kremenchuk', label: 'Кременчук' },
    { value: 'mukachevo', label: 'Мукачево' },
    { value: 'konotop', label: 'Конотоп' },
    { value: 'Умань', label: 'Умань' },
    { value: 'krivyi-rih', label: 'Кривий Ріг' }
].sort((a, b) => a.label.localeCompare(b.label, 'uk'));