export const MBTI = [
    { value: 0, label: 'Виберіть тип MBTI' },
    { value: 1, label: 'Архітектор - INTJ-A / INTJ-T' },
    { value: 2, label: 'Логік - INTP-A / INTP-T' },
    { value: 3, label: 'Командир - ENTJ-A / ENTJ-T' },
    { value: 4, label: 'Полеміст - ENTP-A / ENTP-T' },
    { value: 5, label: 'Адвокат - INFJ-A / INFJ-T' },
    { value: 6, label: 'Посередник - INFP-A / INFP-T' },
    { value: 7, label: 'Протагоніст - ENFJ-A / ENFJ-T' },
    { value: 8, label: 'Активіст - ENFP-A / ENFP-T' },
    { value: 9, label: 'Логіст - ISTJ-A / ISTJ-T' },
    { value: 10, label: 'Захисник - ISFJ-A / ISFJ-T' },
    { value: 11, label: 'Керівник - ESTJ-A / ESTJ-T' },
    { value: 12, label: 'Консул - ESFJ-A / ESFJ-T' },
    { value: 13, label: 'Віртуоз - ISTP-A / ISTP-T' },
    { value: 14, label: 'Авантюрист - ISFP-A / ISFP-T' },
    { value: 15, label: 'Підприємець - ESTP-A / ESTP-T' },
    { value: 16, label: 'Артист - ESFP-A / ESFP-T' },
];