# Generated by Django 5.2.7 on 2026-04-09 13:55

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('country', models.IntegerField(blank=True, choices=[(1, 'Україна')], null=True)),
                ('city', models.IntegerField(blank=True, choices=[(1, 'Київ'), (2, 'Львів'), (3, 'Харків'), (4, 'Одеса'), (5, 'Дніпро'), (6, 'Запоріжжя'), (7, 'Вінниця'), (8, 'Черкаси'), (9, 'Івано-Франківськ'), (10, 'Тернопіль'), (11, 'Рівне'), (12, 'Житомир'), (13, 'Суми'), (14, 'Полтава'), (15, 'Чернігів'), (16, 'Кропивницький'), (17, 'Луцьк'), (18, 'Хмельницький'), (19, 'Миколаїв'), (20, 'Чернівці'), (21, 'Ужгород'), (22, 'Берегове'), (23, "Кам'янець-Подільський"), (24, "Кам'янське"), (25, 'Біла Церква'), (26, 'Бровари'), (27, 'Херсон'), (28, 'Мукачево'), (29, 'Кременчук'), (30, 'Конотоп'), (31, 'Умань'), (32, 'Яремче')], null=True)),
                ('gender', models.IntegerField(blank=True, choices=[(1, 'Чоловік'), (2, 'Жінка'), (3, 'Інша')], null=True)),
                ('birthdate', models.DateField(blank=True, null=True)),
                ('phone_number', models.CharField(blank=True, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'user',
                'managed': True,
            },
        )
    ]
