# Generated by Django 5.2.7 on 2026-03-27 15:26

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('country', models.CharField(blank=True, null=True)),
                ('city', models.CharField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, null=True)),
                ('birthdate', models.DateField(blank=True, null=True)),
                ('phone_number', models.CharField(blank=True, unique=True)),
                ('email', models.EmailField(blank=True, max_length=50, null=True, unique=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'user',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='UserHousing',
            fields=[
                ('housing_id', models.AutoField(primary_key=True, serialize=False)),
                ('room_sharing_preference', models.CharField(max_length=100)),
                ('preferred_gender', models.CharField(max_length=30)),
                ('housing_status', models.CharField(max_length=100)),
                ('budget', models.IntegerField()),
                ('preferred_districts', models.JSONField()),
                ('planned_duration', models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(3)])),
                ('move_in_date', models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(3)])),
                ('has_pet', models.BooleanField()),
                ('pet_description', models.TextField(blank=True, max_length=100, null=True, validators=[django.core.validators.MinLengthValidator(3)])),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='housing', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_housing',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('profile_id', models.AutoField(primary_key=True, serialize=False)),
                ('university', models.CharField(max_length=100)),
                ('specialization', models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(3)])),
                ('study_year', models.CharField(max_length=50)),
                ('languages', models.JSONField()),
                ('political_view', models.JSONField()),
                ('cleanliness', models.IntegerField()),
                ('lifestyle', models.TextField()),
                ('schedule', models.TextField(max_length=100, validators=[django.core.validators.MinLengthValidator(3)])),
                ('sleep_schedule', models.TextField(max_length=100, validators=[django.core.validators.MinLengthValidator(3)])),
                ('bad_habits', models.TextField(max_length=100, validators=[django.core.validators.MinLengthValidator(3)])),
                ('mbti', models.JSONField()),
                ('extra_intro_version', models.CharField(max_length=100)),
                ('hobbies', models.TextField(max_length=200, validators=[django.core.validators.MinLengthValidator(3)])),
                ('bio', models.TextField(max_length=300, validators=[django.core.validators.MinLengthValidator(3)])),
                ('looking_for', models.TextField(max_length=200, validators=[django.core.validators.MinLengthValidator(3)])),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_profile',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='UserPhoto',
            fields=[
                ('image_id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='user_photos/')),
                ('user_profile', models.ForeignKey(db_column='user_profile', on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='user.userprofile')),
            ],
            options={
                'db_table': 'user_photo',
                'managed': True,
            },
        ),
    ]
