# Generated by Django 5.2.7 on 2025-11-24 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table='flat_buddy"."user',
        ),
        migrations.AlterModelTable(
            name='userhousing',
            table='flat_buddy"."user_housing',
        ),
        migrations.AlterModelTable(
            name='userprofile',
            table='flat_buddy"."user_profile',
        ),
    ]
