# Generated by Django 5.2.7 on 2026-04-20 16:05

import django.contrib.postgres.fields
import django.core.validators
import django.db.models.deletion
import user.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='birthdate',
            field=models.DateField(default='1972-01-01'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='city',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='country',
            field=models.IntegerField(choices=[(1, 'Україна')]),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.IntegerField(choices=[(1, 'Чоловік'), (2, 'Жінка'), (3, 'Інша')]),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(unique=True),
        ),
        migrations.CreateModel(
            name='UserHousing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_sharing_preference', models.IntegerField(blank=True, choices=[(1, 'Mені комфортно ділити кімнату з співмешканцем'), (2, 'Я хочу мати окрему кімнату')], null=True)),
                ('preferred_gender', models.IntegerField(blank=True, choices=[(1, 'Лише з хлопцями'), (2, 'Лише з дівчатами'), (3, 'Не має значення')], null=True)),
                ('housing_status', models.IntegerField(blank=True, choices=[(1, 'Я шукаю квартиру та співмешканця'), (2, 'Я шукаю лише співмешканця, маю свою/орендовану квартиру')], null=True)),
                ('budget_min', models.IntegerField(blank=True, null=True)),
                ('budget_max', models.IntegerField(blank=True, null=True)),
                ('destination', models.IntegerField(blank=True, choices=[(1, 'Київ'), (2, 'Львів'), (3, 'Харків'), (4, 'Одеса'), (5, 'Дніпро'), (6, 'Запоріжжя'), (7, 'Вінниця'), (8, 'Черкаси'), (9, 'Івано-Франківськ'), (10, 'Тернопіль'), (11, 'Рівне'), (12, 'Житомир'), (13, 'Суми'), (14, 'Полтава'), (15, 'Чернігів'), (16, 'Кропивницький'), (17, 'Луцьк'), (18, 'Хмельницький'), (19, 'Миколаїв'), (20, 'Чернівці'), (21, 'Ужгород'), (22, 'Берегове'), (23, "Кам'янець-Подільський"), (24, "Кам'янське"), (25, 'Біла Церква'), (26, 'Бровари'), (27, 'Херсон'), (28, 'Мукачево'), (29, 'Кременчук'), (30, 'Конотоп'), (31, 'Умань'), (32, 'Яремче')], null=True)),
                ('preferred_districts', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True, choices=[(1, 'Голосіївський'), (2, 'Дарницький'), (3, 'Деснянський'), (4, 'Дніпровський'), (5, 'Оболонський'), (6, 'Печерський'), (7, 'Подільський'), (8, 'Святошинський'), (9, 'Солом’янський'), (10, 'Шевченківський'), (11, 'Галицький'), (12, 'Залізничний'), (13, 'Личаківський'), (14, 'Сихівський'), (15, 'Франківський'), (16, 'Шевченківський'), (17, 'Холодногірський'), (18, 'Шевченківський'), (19, 'Київський'), (20, 'Салтівський'), (21, 'Немишлянський'), (22, 'Індустріальний'), (23, 'Слобідський'), (24, 'Основ’янський'), (25, 'Новобаварський'), (26, 'Київський'), (27, 'Хаджибейський'), (28, 'Приморський'), (29, 'Пересипський'), (30, 'Амур-Нижньодніпровський'), (31, 'Шевченківський'), (32, 'Соборний'), (33, 'Індустріальний'), (34, 'Центральний'), (35, 'Чечелівський'), (36, 'Новокодацький'), (37, 'Самарський'), (38, 'Заводський'), (39, 'Хортицький'), (40, 'Комунарський'), (41, 'Дніпровський'), (42, 'Олександрівський'), (43, 'Вознесенівський'), (44, 'Шевченківський'), (45, 'Замостянський'), (46, 'Лівобережний'), (47, 'Староміський'), (48, 'Придніпровський'), (49, 'Соснівський'), (50, 'Центральний'), (51, 'Пасічна'), (52, 'БАМ'), (53, 'Каскад'), (54, 'Заріччя'), (55, 'Центр'), (56, 'Дружба'), (57, 'Аляска'), (58, 'Східний'), (59, 'Сонячний'), (60, 'Новий Світ'), (61, 'Центр'), (62, 'Ювілейний'), (63, 'Боярка'), (64, 'Північний'), (65, 'Щасливий'), (66, 'Богунський'), (67, 'Корольовський'), (68, 'Зарічний'), (69, 'Ковпаківський'), (70, 'Шевченківський'), (71, 'Київський'), (72, 'Подільський'), (73, 'Деснянський'), (74, 'Новозаводський'), (75, 'Фортечний'), (76, 'Подільський'), (77, 'Центр'), (78, 'Затишний'), (79, 'Першотравневий'), (80, 'Садгірський'), (81, 'Шевченківський'), (82, 'Центральний'), (83, 'Минайський'), (84, 'Боздоський'), (85, 'Радванський'), (86, 'Центральний'), (87, 'Зарічний'), (88, 'Староміський'), (89, 'Новоплановський'), (90, 'Баглійський'), (91, 'Дніпровський'), (92, 'Заводський'), (93, 'Центральний'), (94, 'Мікрорайон Південний'), (95, 'Мікрорайон Північний'), (96, 'Центральний'), (97, 'Південний'), (98, 'Північний'), (99, 'Дніпровський'), (100, 'Суворовський'), (101, 'Корабельний'), (102, 'Центральний'), (103, 'Заводський'), (104, 'Інгульський'), (105, 'Корабельний'), (106, 'Центральний'), (107, 'Південно-Західний')], null=True), blank=True, default=list, size=10)),
                ('planned_duration', models.IntegerField(blank=True, choices=[(1, 'Менше 6 місяців'), (2, 'Від 6 до 12 місяців'), (3, 'Більше 1 року')], null=True)),
                ('move_in_date', models.DateField(blank=True, null=True)),
                ('has_pet', models.BooleanField(default=False)),
                ('pet_description', models.TextField(blank=True, max_length=100, null=True, validators=[django.core.validators.MinLengthValidator(3)])),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='housing', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_housing',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(blank=True, choices=[(1, 'Студент'), (2, 'Працюю'), (3, 'Студент і працюю')], null=True)),
                ('orbit', models.IntegerField(blank=True, choices=[(1, 'STEM та IT'), (2, 'Бізнес та Управління'), (3, 'Соціальні науки та гуманітарні дисципліни'), (4, 'Здоров’я та спорт'), (5, 'Творча індустрія та дизайн'), (6, 'Освіта та педагогіка'), (7, 'Сфера послуг'), (8, 'Військова справа, безпека та правоохоронні органи'), (9, 'Медицина та охорона здоров’я')], null=True)),
                ('languages', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, choices=[('en', 'English'), ('uk', 'Українська'), ('fr', 'Français'), ('de', 'Deutsch'), ('es', 'Español'), ('pl', 'Polski'), ('it', 'Italiano'), ('pt', 'Português'), ('ar', 'العربية'), ('ja', '日本語'), ('ko', '한국어'), ('zh', '中文'), ('ru', 'Русский'), ('tr', 'Türkçe'), ('nl', 'Nederlands'), ('cs', 'Čeština'), ('sk', 'Slovenčina'), ('hu', 'Magyar'), ('ro', 'Română'), ('bg', 'Български'), ('sv', 'Svenska'), ('hr', 'Hrvatski')], max_length=2, null=True, validators=[django.core.validators.MinLengthValidator(2)]), default=list, size=5)),
                ('political_coordinate_economic', models.IntegerField(blank=True, null=True)),
                ('political_coordinate_social', models.IntegerField(blank=True, null=True)),
                ('cleanliness', models.IntegerField(blank=True, null=True)),
                ('my_vibe', models.TextField(blank=True, max_length=600, validators=[django.core.validators.MinLengthValidator(200)])),
                ('buddy_vibe', models.TextField(blank=True, max_length=600, validators=[django.core.validators.MinLengthValidator(200)])),
                ('schedule', models.TextField(blank=True, max_length=100, validators=[django.core.validators.MinLengthValidator(3)])),
                ('sleep_schedule', models.TextField(blank=True, max_length=100, validators=[django.core.validators.MinLengthValidator(3)])),
                ('smoking', models.IntegerField(blank=True, choices=[(1, 'Палю'), (2, 'Іноді палю'), (3, 'Не палю, але це не проблема для мене'), (4, 'Проти паління')], null=True)),
                ('extra_intro_version', models.IntegerField(blank=True, choices=[(-1, 'Інтроверт'), (0, 'Амбіверт'), (1, 'Екстраверт')], null=True)),
                ('hobbies', models.IntegerField(blank=True, choices=[(1, 'Фітнес / Тренажерний зал'), (2, 'Біг / Легка атлетика'), (3, 'Йога / Медитація'), (4, 'Велоспорт'), (5, 'Командні види спорту'), (6, 'Бойові мистецтва'), (7, 'Походи / Гори'), (8, 'Музика / Гра на інструментах'), (9, 'Фотографія / Відео'), (10, 'Малювання / Дизайн'), (11, 'Рукоділля / DIY'), (12, 'Письменництво / Блогінг'), (13, 'Відеоігри'), (14, 'Настільні ігри'), (15, 'Кіно та Серіали'), (16, 'Аніме / Манга'), (17, 'Книги / Література'), (18, 'Кулінарія / Випічка'), (19, 'Подорожі / Туризм'), (20, 'Домашні тварини'), (21, 'Кімнатні рослини'), (22, 'Волонтерство'), (23, 'Технології / Програмування'), (24, 'Вивчення мов'), (25, 'Мода / Стиль')], null=True)),
                ('partying', models.IntegerField(blank=True, choices=[(1, 'Люблю вечірки/гостей'), (2, 'Іноді люблю вечірки/гостей'), (3, 'Це не проблема для мене'), (4, 'Проти вечірок/гостей')], null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_profile',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='UserPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=user.models.user_directory_path)),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='user.userprofile')),
            ],
            options={
                'db_table': 'user_photo',
            },
        ),
    ]
