# Generated by Django 5.2.7 on 2025-11-24 14:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name="Ім'я")),
                ('last_name', models.CharField(max_length=50, verbose_name='Прізвище')),
                ('country', models.CharField(max_length=50, verbose_name='Країна')),
                ('city', models.CharField(max_length=50, verbose_name='Місто')),
                ('gender', models.CharField(choices=[('Чоловік', 'Чоловік'), ('Жінка', 'Жінка'), ('Інше', 'Інше')], max_length=10, verbose_name='Стать')),
                ('birthdate', models.DateField(verbose_name='Дата народження')),
                ('phone_number', models.CharField(max_length=13, unique=True, verbose_name='Номер телефону')),
                ('email', models.EmailField(max_length=100, unique=True, verbose_name='Email')),
                ('password_hash', models.CharField(max_length=255, verbose_name='Хеш пароля')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
            ],
            options={
                'verbose_name': 'Користувач',
                'verbose_name_plural': 'Користувачі',
                'db_table': 'flat_buddy.user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserHousing',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='housing', serialize=False, to='user.user', verbose_name='Користувач')),
                ('room_sharing_preference', models.CharField(choices=[('Mені комфортно ділити кімнату з співмешканцем', 'Mені комфортно ділити кімнату з співмешканцем'), ('Я хочу мати окрему кімнату', 'Я хочу мати окрему кімнату')], max_length=100, verbose_name='Чому надаєте перевагу?')),
                ('preferred_gender', models.CharField(choices=[('Лише з хлопцями', 'Лише з хлопцями'), ('Лише з дівчатами', 'Лише з дівчатами'), ('Не має значення', 'Не має значення')], max_length=30, verbose_name='Із ким ви б хотіли проживати?')),
                ('housing_status', models.CharField(choices=[('Я шукаю квартиру та співмешканця', 'Я шукаю квартиру та співмешканця'), ('Я шукаю лише співмешканця, маю свою/орендовану квартиру', 'Я шукаю лише співмешканця, маю свою/орендовану квартиру')], max_length=100, verbose_name='Що найкраще описує вашу ситуацію?')),
                ('budget', models.IntegerField(verbose_name='Який ваш бюджет?')),
                ('preferred_districts', models.JSONField(verbose_name='Оберіть бажаний район/райони проживання')),
                ('planned_duration', models.CharField(max_length=50, verbose_name='Як довго ви плануєте проживати у орендованій квартирі?')),
                ('move_in_date', models.CharField(max_length=100, verbose_name='Коли б ви хотіли заїхати у квартиру?')),
                ('has_pet', models.BooleanField(verbose_name='Чи є у вас домашній улюбленець?')),
                ('pet_description', models.TextField(blank=True, null=True, verbose_name='Розкажіть про своїх домашніх улюбленців')),
            ],
            options={
                'verbose_name': 'Житлові уподобання',
                'verbose_name_plural': 'Житлові уподобання',
                'db_table': 'flat_buddy.user_housing',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='profile', serialize=False, to='user.user', verbose_name='Користувач')),
                ('profile_photo_url', models.TextField(verbose_name='Фото профілю')),
                ('university', models.CharField(max_length=100, verbose_name='Заклад освіти')),
                ('specialization', models.CharField(max_length=50, verbose_name='Спеціалізація')),
                ('study_year', models.CharField(max_length=50, verbose_name='Курс')),
                ('languages', models.JSONField(verbose_name='Допустимі мови спілкування')),
                ('political_view', models.CharField(max_length=100, verbose_name='Політичні погляди')),
                ('cleanliness', models.IntegerField(choices=[(1, '1 (Дуже неохайно)'), (2, '2'), (3, '3 (Середньо)'), (4, '4'), (5, '5 (Дуже охайно)')], verbose_name='Охайність (1-5)')),
                ('lifestyle', models.TextField(verbose_name='Опишіть свій стиль життя')),
                ('schedule', models.TextField(verbose_name='Розклад')),
                ('sleep_schedule', models.TextField(verbose_name='Графік сну')),
                ('bad_habits', models.TextField(verbose_name='Шкідливі звички')),
                ('mbti', models.JSONField(verbose_name='MBTI')),
                ('extra_intro_version', models.CharField(max_length=50, verbose_name='Екстравертність/інтровертність')),
                ('hobbies', models.TextField(verbose_name='Розкажіть про ваші захоплення/хобі')),
                ('bio', models.TextField(verbose_name='Біо')),
                ('looking_for', models.TextField(verbose_name='Кого шукаєте')),
            ],
            options={
                'verbose_name': 'Профіль користувача',
                'verbose_name_plural': 'Профілі користувачів',
                'db_table': 'flat_buddy.user_profile',
                'managed': False,
            },
        ),
    ]
