# Generated by Django 5.2.7 on 2025-11-30 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPhoto',
            fields=[
                ('image_id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='media/user_photos/', verbose_name='Фото профілю')),
            ],
            options={
                'verbose_name': 'Фото профілю',
                'db_table': 'flat_buddy"."user_photo',
                'managed': False,
            },
        ),
    ]
